export const SET_AUTH_USER_DATA = "SET_AUTH_USER_DATA",
  SET_LOGIN_DATA = "SET_LOGIN_DATA",
  SET_LOADING = "SET_LOADING",
  SET_LOGOUT_DATA = "SET_LOGOUT_DATA",
  SET_ERROR_TEXT = "SET_ERROR_TEXT";
