export const FOLLOW = "FOLLOW",
	UNFOLLOW = "UNFOLLOW",
	SET_USERS = "SET_USERS",
	SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
	SET_TOTAL_USERS_COUNT = "SET_TOTAL_USERS_COUNT",
	SET_LOADING = "SET_LOADING",
	FOLLOWING_PROCESSING = "FOLLOWING_PROCESSING";


