export const ADD_POST = "ADD-POST",
	UPDATE_POST_TEXT = "UPDATE-NEW-POST-TEXT",
	SET_USER_PROFILE = "SET_USER_PROFILE",
	PROFILE_LOADING = "PROFILE_LOADING",
	EDIT_STATUS_TEXT = "EDIT_STATUS_TEXT",
	SET_STATUS_TEXT = "SET_STATUS_TEXT",
	CANCEL_SET_STATUS = "CANCEL_SET_STATUS",
	SET_STATUS_FROM_SERVER = "SET_STATUS_FROM_SERVER";

